#!/bin/bash

echo "========================================="
echo "Testing Silent Installer"
echo "========================================="
echo ""
echo "Test command:"
echo ""
echo "export KANASA_SERVER_KEY=usa-st-louis"
echo "export KANASA_WG_PORT=7932"
echo "export KANASA_WG_SUBNET=10.30.31.0/24"
echo "curl -fsSL https://raw.githubusercontent.com/rachidb13/kanasa_vps_setup/001-silent-installer-mode/run-silent.sh | bash"
echo ""
echo "========================================="
echo "Expected Output:"
echo "========================================="
echo ""
echo "  ✔ Done"
echo "  ✔ Done"
echo "  ✔ Done"
echo "  ✔ Done"
echo ""
echo "✅ Country flag module installed successfully"
echo ""
echo "🔍 Gathering server details..."
echo ""
echo "========================================================"
echo "       📝 SERVER REGISTRATION PAYLOAD 📝"
echo "========================================================"
echo "..."
echo ""
echo "========================================="
echo "What to Check:"
echo "========================================="
echo ""
echo "✅ NO false '❌ Setup failed' messages"
echo "✅ Four '✔ Done' messages (one per step)"
echo "✅ Final success message"
echo "✅ JSON payload displayed"
echo ""
echo "========================================="
echo "If you still see errors:"
echo "========================================="
echo ""
echo "1. GitHub may be caching the file"
echo "2. Wait 1-2 minutes for cache to clear"
echo "3. Or use direct branch URL:"
echo "   https://raw.githubusercontent.com/rachidb13/kanasa_vps_setup/001-silent-installer-mode/run-silent.sh"
echo ""

